/*
 * Ventana de login principal
 */
package grafica;

import DAO.DAOLogin;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import com.mycompany.polideportivo_alejandro.Persona;
import com.mycompany.polideportivo_alejandro.Usuario;

/**
 *
 * @author Alex
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagen_fondo = new javax.swing.JLayeredPane();
        Confirmación = new javax.swing.JButton();
        nombreUsuario = new javax.swing.JLabel();
        opcionNombre = new javax.swing.JTextField();
        contraseña = new javax.swing.JLabel();
        nombre_contraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        imagen_fondo.setFocusCycleRoot(true);

        Confirmación.setText("ENTRAR");
        Confirmación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmaciónActionPerformed(evt);
            }
        });
        imagen_fondo.setLayer(Confirmación, javax.swing.JLayeredPane.MODAL_LAYER);
        imagen_fondo.add(Confirmación);
        Confirmación.setBounds(390, 380, 140, 23);

        nombreUsuario.setText("USUARIO ");
        nombreUsuario.setMaximumSize(new java.awt.Dimension(52, 20));
        nombreUsuario.setMinimumSize(new java.awt.Dimension(52, 20));
        imagen_fondo.setLayer(nombreUsuario, javax.swing.JLayeredPane.MODAL_LAYER);
        imagen_fondo.add(nombreUsuario);
        nombreUsuario.setBounds(260, 150, 90, 60);

        opcionNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionNombreActionPerformed(evt);
            }
        });
        imagen_fondo.setLayer(opcionNombre, javax.swing.JLayeredPane.MODAL_LAYER);
        imagen_fondo.add(opcionNombre);
        opcionNombre.setBounds(330, 170, 280, 30);

        contraseña.setText("CONTRASEÑA");
        imagen_fondo.setLayer(contraseña, javax.swing.JLayeredPane.MODAL_LAYER);
        imagen_fondo.add(contraseña);
        contraseña.setBounds(250, 290, 90, 16);
        imagen_fondo.add(nombre_contraseña);
        nombre_contraseña.setBounds(340, 282, 270, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmaciónActionPerformed
         String nombre = opcionNombre.getText().trim();
        String password = nombre_contraseña.getText().trim();

        if (nombre.isBlank() || password.isBlank()) {
            JOptionPane.showMessageDialog(this, "Tiene que introducir usuario y contraseña", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            //Creo un objeto para confirmar el logín
            DAOLogin login = new DAOLogin();
            //creo un usuario con el login.
            Usuario usuario_login = login.confirmacionLogin(nombre, password);
            //Compruebo que no sean datos inválidos
            if (usuario_login != null) {
                //Compruebo si es administrador con el objeto usuario y booleano de la BD.
                if (usuario_login.es_Admin()) {
                    ventAdmin ventana = new ventAdmin(usuario_login);
                    dispose();
                    ventana.setVisible(true);
                } else {
                    ventUsuario vusuario = new ventUsuario(usuario_login);
                    dispose();
                    vusuario.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Login fallido", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_ConfirmaciónActionPerformed

    private void opcionNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirmación;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLayeredPane imagen_fondo;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JPasswordField nombre_contraseña;
    private javax.swing.JTextField opcionNombre;
    // End of variables declaration//GEN-END:variables
}
