/*
 * 
 */
package grafica;

import DAO.DAODeporte;
import DAO.DAOPersona;
import DAO.DAOUsuario;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import com.mycompany.polideportivo_alejandro.Deporte;
import com.mycompany.polideportivo_alejandro.Persona;
import com.mycompany.polideportivo_alejandro.Usuario;
import java.time.OffsetTime;

/**
 *
 * @author usuarioDAW
 */
public class ventAdmin extends javax.swing.JFrame {

    private Usuario admin;
    private List<Persona> personas;
    private List<Deporte> listaDeportes;
    private DefaultComboBoxModel<String> opcionD,opcionD2,opcionD3;

    /**
     * Creates new form ventAdmin
     */
    public ventAdmin(Usuario admin) {
        initComponents();
        opcionD = new DefaultComboBoxModel<>();
        opcionD2 = new DefaultComboBoxModel<>();
        opcionD3 = new DefaultComboBoxModel<>();
        opcionD.removeAllElements();
        cargarLista();
        rellenarDeporte();
        this.admin = admin;
        //Relleno la primera opción vacía.
        opcionD.addElement("-Usa esta opción si no quiere un deporte-");
        opcionD2.addElement("-Usa esta opción si no quiere un deporte-");
        opcionD3.addElement("-Usa esta opción si no quiere un deporte-");
        
        //Introduzco la lista en cada uno de los Jcombo.
        opcionDeporte.setModel(opcionD);
        opcionDeporte2.setModel(opcionD2);
        opcionDeporte3.setModel(opcionD3);
        Nombre.setText(admin.getUsername());
        NombreUsuario.setEnabled(false);
        apellido1.setEnabled(false);
        apellido2.setEnabled(false);
        num_contact.setEnabled(false);
        edad.setEnabled(false);
        categoria.setEnabled(false);
        f_nac_cambio.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        opciones = new javax.swing.JTabbedPane();
        consultar = new javax.swing.JPanel();
        BotonBuscar = new javax.swing.JButton();
        dni = new javax.swing.JLabel();
        campoDni = new javax.swing.JTextField();
        infoPersona = new javax.swing.JPanel();
        etiquetaNombre = new javax.swing.JLabel();
        NombreUsuario = new javax.swing.JTextField();
        etiquetaApellido = new javax.swing.JLabel();
        apellido1 = new javax.swing.JTextField();
        etiquetaApellido2 = new javax.swing.JLabel();
        apellido2 = new javax.swing.JTextField();
        etiquetancontact = new javax.swing.JLabel();
        num_contact = new javax.swing.JTextField();
        etiquetaEdad = new javax.swing.JLabel();
        edad = new javax.swing.JTextField();
        etiquetaCat = new javax.swing.JLabel();
        categoria = new javax.swing.JTextField();
        f_nac_cambio = new com.github.lgooddatepicker.components.DatePicker();
        etiqueta_f_nac_cambio = new javax.swing.JLabel();
        Modificar = new javax.swing.JButton();
        Crear = new javax.swing.JPanel();
        etiquetaNombre1 = new javax.swing.JLabel();
        NombreUsuario1 = new javax.swing.JTextField();
        etiquetaApellido1 = new javax.swing.JLabel();
        apellido3 = new javax.swing.JTextField();
        etiquetaApellido3 = new javax.swing.JLabel();
        apellido4 = new javax.swing.JTextField();
        etiquetancontact1 = new javax.swing.JLabel();
        num_contact1 = new javax.swing.JTextField();
        etiquetaf_nac = new javax.swing.JLabel();
        Crear_Usuario = new javax.swing.JButton();
        DNI = new javax.swing.JLabel();
        campoDNI = new javax.swing.JTextField();
        Deporte1 = new javax.swing.JLabel();
        Deporte2 = new javax.swing.JLabel();
        Deporte3 = new javax.swing.JLabel();
        recordatorio = new javax.swing.JLabel();
        opcionDeporte = new javax.swing.JComboBox<>();
        opcionDeporte3 = new javax.swing.JComboBox<>();
        opcionDeporte2 = new javax.swing.JComboBox<>();
        fecha_nac = new com.github.lgooddatepicker.components.DatePicker();
        etiquetaDNI = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoDNI3 = new javax.swing.JTextField();
        EliminarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        consultar.setForeground(new java.awt.Color(204, 0, 51));

        BotonBuscar.setText("Buscar");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });

        dni.setText("DNI");

        campoDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDniActionPerformed(evt);
            }
        });

        etiquetaNombre.setText("Nombre");

        NombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreUsuarioActionPerformed(evt);
            }
        });

        etiquetaApellido.setText("Apellido");

        apellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellido1ActionPerformed(evt);
            }
        });

        etiquetaApellido2.setText("Apellido 2º");

        etiquetancontact.setText("Nº contacto");

        etiquetaEdad.setText("Edad");

        etiquetaCat.setText("Categoria");

        etiqueta_f_nac_cambio.setText("Fecha nacimiento");

        javax.swing.GroupLayout infoPersonaLayout = new javax.swing.GroupLayout(infoPersona);
        infoPersona.setLayout(infoPersonaLayout);
        infoPersonaLayout.setHorizontalGroup(
            infoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPersonaLayout.createSequentialGroup()
                .addGroup(infoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, infoPersonaLayout.createSequentialGroup()
                        .addComponent(etiquetaCat, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(categoria))
                    .addGroup(infoPersonaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(infoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(infoPersonaLayout.createSequentialGroup()
                                .addComponent(etiquetaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(infoPersonaLayout.createSequentialGroup()
                                .addGroup(infoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetancontact, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etiquetaEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etiquetaApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etiquetaApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(infoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(apellido2, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(num_contact)
                                    .addComponent(edad)
                                    .addComponent(apellido1, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(228, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPersonaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(infoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPersonaLayout.createSequentialGroup()
                        .addComponent(etiqueta_f_nac_cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPersonaLayout.createSequentialGroup()
                        .addComponent(f_nac_cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        infoPersonaLayout.setVerticalGroup(
            infoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPersonaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(infoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombre)
                    .addComponent(NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaApellido)
                    .addComponent(apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaApellido2)
                    .addComponent(apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetancontact)
                    .addComponent(num_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(infoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaEdad)
                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(infoPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCat)
                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(etiqueta_f_nac_cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f_nac_cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultarLayout = new javax.swing.GroupLayout(consultar);
        consultar.setLayout(consultarLayout);
        consultarLayout.setHorizontalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(consultarLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoDni, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(consultarLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(BotonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        consultarLayout.setVerticalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        opciones.addTab("Consultar", consultar);

        etiquetaNombre1.setText("Nombre");

        NombreUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreUsuario1ActionPerformed(evt);
            }
        });

        etiquetaApellido1.setText("Apellido");

        etiquetaApellido3.setText("Apellido 2º");

        etiquetancontact1.setText("Nº contacto");

        etiquetaf_nac.setText("Fecha nac:");

        Crear_Usuario.setText("CREAR");
        Crear_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_UsuarioActionPerformed(evt);
            }
        });

        DNI.setText("DNI");

        campoDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDNIActionPerformed(evt);
            }
        });

        Deporte1.setText("Deporte");

        Deporte2.setText("Deporte");

        Deporte3.setText("Deporte");

        recordatorio.setText("Año/Mes/Dia");

        opcionDeporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionDeporteActionPerformed(evt);
            }
        });

        opcionDeporte3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        opcionDeporte3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionDeporte3ActionPerformed(evt);
            }
        });

        opcionDeporte2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        opcionDeporte2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionDeporte2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CrearLayout = new javax.swing.GroupLayout(Crear);
        Crear.setLayout(CrearLayout);
        CrearLayout.setHorizontalGroup(
            CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Crear_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(CrearLayout.createSequentialGroup()
                        .addGroup(CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CrearLayout.createSequentialGroup()
                                .addGroup(CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CrearLayout.createSequentialGroup()
                                        .addGroup(CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Deporte1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Deporte2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(CrearLayout.createSequentialGroup()
                                        .addComponent(etiquetaf_nac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(26, 26, 26)))
                                .addGroup(CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(campoDNI, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(opcionDeporte, javax.swing.GroupLayout.Alignment.LEADING, 0, 157, Short.MAX_VALUE)
                                        .addComponent(opcionDeporte2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(fecha_nac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE))
                            .addGroup(CrearLayout.createSequentialGroup()
                                .addGroup(CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(CrearLayout.createSequentialGroup()
                                        .addGroup(CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(CrearLayout.createSequentialGroup()
                                                .addComponent(etiquetaApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(16, 16, 16))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearLayout.createSequentialGroup()
                                                .addComponent(etiquetaNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)))
                                        .addGroup(CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(apellido3, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                            .addComponent(NombreUsuario1)))
                                    .addGroup(CrearLayout.createSequentialGroup()
                                        .addComponent(Deporte3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(opcionDeporte3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(CrearLayout.createSequentialGroup()
                                        .addGroup(CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(etiquetancontact1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(etiquetaApellido3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(num_contact1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                            .addComponent(apellido4))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(recordatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        CrearLayout.setVerticalGroup(
            CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombre1)
                    .addComponent(NombreUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaApellido1)
                    .addComponent(apellido3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaApellido3)
                    .addComponent(apellido4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetancontact1)
                    .addComponent(num_contact1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaf_nac)
                    .addComponent(recordatorio)
                    .addComponent(fecha_nac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DNI)
                    .addComponent(campoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deporte1)
                    .addComponent(opcionDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deporte2)
                    .addComponent(opcionDeporte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deporte3)
                    .addComponent(opcionDeporte3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(Crear_Usuario)
                .addGap(27, 27, 27))
        );

        opciones.addTab("Crear", Crear);

        jLabel1.setText("DNI");

        EliminarBoton.setText("Eliminar");
        EliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout etiquetaDNILayout = new javax.swing.GroupLayout(etiquetaDNI);
        etiquetaDNI.setLayout(etiquetaDNILayout);
        etiquetaDNILayout.setHorizontalGroup(
            etiquetaDNILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(etiquetaDNILayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(campoDNI3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, etiquetaDNILayout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addComponent(EliminarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        etiquetaDNILayout.setVerticalGroup(
            etiquetaDNILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(etiquetaDNILayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(etiquetaDNILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoDNI3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 373, Short.MAX_VALUE)
                .addComponent(EliminarBoton)
                .addGap(34, 34, 34))
        );

        opciones.addTab("Eliminar", etiquetaDNI);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(opciones)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opciones))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreUsuario1ActionPerformed

    private void campoDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDniActionPerformed

    }//GEN-LAST:event_campoDniActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        String dni = campoDni.getText().trim();
        Persona persona = null;
        boolean encontrado = false;
        if (dni.isBlank() || dni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduce un dni", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            for (Persona p : personas) {
                if (dni.equalsIgnoreCase(p.getDni())) {
                    NombreUsuario.setEnabled(true);
                    NombreUsuario.setText(p.getNombre());
                    apellido1.setText(p.getApellido1());
                    apellido2.setText(p.getApellido2());
                    num_contact.setText(p.getNum_contacto());
                    edad.setText(String.valueOf(p.getEdad()));
                     categoria.setText(p.getCategoria().toString());
                    f_nac_cambio.setText(p.getF_nac().toString());
                    encontrado = true;
                }
            }
            if (!encontrado) {
                JOptionPane.showMessageDialog(this, "no se ha encontrado ningun usuario con ese dni",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
                  System.out.println(personas.getLast().toString());
                apellido1.setEnabled(true);
                apellido2.setEnabled(true);
                num_contact.setEnabled(true);
                categoria.setEnabled(true);
                f_nac_cambio.setEnabled(true);
    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        String Dni= campoDni.getText().trim().toUpperCase();
        int i=0;
        boolean encontrado=false,actualizado=false;
        Persona p1= null;
        while(i<personas.size()&&!encontrado){
            p1=personas.get(i);
            i++;
            if (Dni.equalsIgnoreCase(p1.getDni())&& !encontrado) {
             try{
                  if (NombreUsuario.getText().isBlank() || apellido1.getText().isBlank()
                    || apellido2.getText().isBlank() || campoDni.getText().isBlank()
                    || num_contact.getText().isBlank()) {
                      JOptionPane.showMessageDialog(this, "No deje campos sin rellenar",
                        "Error", JOptionPane.ERROR_MESSAGE);
                  }else{
                      //Uso la información base del boton buscar
                    String nombre = NombreUsuario.getText().trim();
                    String ap1 = apellido1.getText().trim();
                    String ap2 = apellido2.getText().trim();
                    String dni2 = campoDni.getText().trim();        
                    String num_contact2 = num_contact.getText().trim();
                    LocalDate hoy= LocalDate.now();
                    LocalDate f_nac = f_nac_cambio.getDate();
                        //Aviso para que no dejen el campo fecha vacío.
                    if (f_nac == null|| f_nac.isAfter(hoy)){
                        JOptionPane.showMessageDialog(this, "Introduzca la fecha de nacimiento que no sea después del dia de hoy",
                        "Error", JOptionPane.INFORMATION_MESSAGE);
                    }
                    Persona p = new Persona(nombre, ap1, ap2, dni2, num_contact2, f_nac);
                      
                    DAOPersona dao = new DAOPersona();
                    dao.actualizarPersona(p);
                    p1.setNombre(nombre);
                    p1.setApellido1(ap1);
                    p1.setApellido2(ap2);
                    p1.setDni(dni2);
                JOptionPane.showMessageDialog(this, "Datos modificados correctamente");
                   // p2 = p1;
                    //personas.rep(p1);
                    encontrado = true;
                  }
             }catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error de validación", JOptionPane.ERROR_MESSAGE);
            }
            }
            
        }
            if(!encontrado){
                JOptionPane.showMessageDialog(this, "El dni introducido no pertenece a nadie", "Error", JOptionPane.INFORMATION_MESSAGE);
                encontrado=true;
            }
         /*   if(encontrado&& !actualizado){
              //Borro e inserto para actualizar la lista.
                    personas.remove(p2);
                    personas.add(p2);  
                    actualizado=true;
            }*/
        
    }//GEN-LAST:event_ModificarActionPerformed

    private void Crear_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_UsuarioActionPerformed
        //Recojo el dni del JtextField
        String Dni = campoDNI.getText().trim();
        //Recorro la lista
        for (Persona p1 : personas) {
            //Comprobación que el dni no exista ya en la BD.
            if (Dni.equalsIgnoreCase(p1.getDni())) {
                JOptionPane.showMessageDialog(this, "Ese dni ya pertenece a alguien en el sistema",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        try {
            //Comprobaciones para que no quede ningun campo libre.
            if (!(NombreUsuario.getText().isBlank() || apellido3.getText().isBlank()
                    || apellido4.getText().isBlank() || campoDNI.getText().isBlank()
                    || num_contact.getText().isBlank())) {
                /*Asigno los parámetros de entrada, para añadirlos 
                    al constructor del DAO, para el prepared*/
                String nombre = NombreUsuario1.getText().trim();
                String ap1 = apellido3.getText().trim();
                String ap2 = apellido4.getText().trim();
               
                String num_contact2 = num_contact1.getText().trim();
                LocalDate hoy= LocalDate.now();
                LocalDate f_nac = (LocalDate) fecha_nac.getDate();
             
                boolean datosValidos = true;
                if(f_nac.isAfter(hoy)){
                    JOptionPane.showMessageDialog(this, "La fecha de nacimiento no puede se mayor a la de hoy",
                        "Error", JOptionPane.ERROR_MESSAGE);
                    datosValidos=false;
                }
                Persona p = new Persona(nombre, ap1, ap2, Dni, num_contact2, f_nac);
                
                DAOPersona dao = new DAOPersona();
                //Paso el objeto persona al método de insertar
                dao.insertarPersona(p);
                //Relleno la lista.
                personas.add(p);
                //Preparo la consulta para añadir los deportes elegidos.
                String deporte1=(String)opcionDeporte.getSelectedItem();
                String deporte2=(String)opcionDeporte2.getSelectedItem();
                String deporte3=(String)opcionDeporte3.getSelectedItem();
                //Creo el objeto deporte con el nombre
                Deporte dp= new Deporte(deporte1);
                DAODeporte dao1 = new DAODeporte();
                if (!deporte1.equals("Selecciona deporte")) {
                dao1.insertarDeporte(Dni,deporte1);
                }
                
                DAODeporte dao3 = new DAODeporte();
                if (!deporte2.equals("Selecciona deporte")) {
                dao3.insertarDeporte(Dni,deporte2);
                }
                
                DAODeporte dao4 = new DAODeporte();
                if (!deporte3.equals("Selecciona deporte")) {
                dao4.insertarDeporte(Dni,deporte3);
                }
                 //Insertar Usuario
                 Usuario u1= new Usuario(nombre,(ap1+"50"));
                 DAOUsuario dao2=new DAOUsuario();
                 dao2.insertarUsuario(Dni,(nombre+ap2), (ap1+"50"));
                 
                JOptionPane.showMessageDialog(this, "Usuario registrado",
                        "Bien", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(this, "No dejes campos en blanco.",
                        "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            }

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error de validación", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Crear_UsuarioActionPerformed

    private void opcionDeporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionDeporteActionPerformed
       
    }//GEN-LAST:event_opcionDeporteActionPerformed

    private void opcionDeporte3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionDeporte3ActionPerformed
     
    }//GEN-LAST:event_opcionDeporte3ActionPerformed

    private void opcionDeporte2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionDeporte2ActionPerformed
      
    }//GEN-LAST:event_opcionDeporte2ActionPerformed

    private void NombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreUsuarioActionPerformed

    private void apellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellido1ActionPerformed

    private void EliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBotonActionPerformed
        String Dni = campoDNI3.getText().trim();
        boolean encontrado = false;
        Persona personaBorrada = null;
        for (Persona p1 : personas) {
            if (Dni.equalsIgnoreCase(p1.getDni())) {
                personaBorrada = p1;
                encontrado = true;
            }
        }
        if (encontrado) {
            DAOPersona dao = new DAOPersona();
            dao.eliminarPersona(Dni);
            personas.remove(personaBorrada);
            JOptionPane.showMessageDialog(this, "Borrado correctamente",
                    "Bien", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Ese dni no pertenece a nadie en el sistema",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EliminarBotonActionPerformed

    private void campoDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDNIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JPanel Crear;
    private javax.swing.JButton Crear_Usuario;
    private javax.swing.JLabel DNI;
    private javax.swing.JLabel Deporte1;
    private javax.swing.JLabel Deporte2;
    private javax.swing.JLabel Deporte3;
    private javax.swing.JButton EliminarBoton;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField NombreUsuario;
    private javax.swing.JTextField NombreUsuario1;
    private javax.swing.JTextField apellido1;
    private javax.swing.JTextField apellido2;
    private javax.swing.JTextField apellido3;
    private javax.swing.JTextField apellido4;
    private javax.swing.JTextField campoDNI;
    private javax.swing.JTextField campoDNI3;
    private javax.swing.JTextField campoDni;
    private javax.swing.JTextField categoria;
    private javax.swing.JPanel consultar;
    private javax.swing.JLabel dni;
    private javax.swing.JTextField edad;
    private javax.swing.JLabel etiquetaApellido;
    private javax.swing.JLabel etiquetaApellido1;
    private javax.swing.JLabel etiquetaApellido2;
    private javax.swing.JLabel etiquetaApellido3;
    private javax.swing.JLabel etiquetaCat;
    private javax.swing.JPanel etiquetaDNI;
    private javax.swing.JLabel etiquetaEdad;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaNombre1;
    private javax.swing.JLabel etiqueta_f_nac_cambio;
    private javax.swing.JLabel etiquetaf_nac;
    private javax.swing.JLabel etiquetancontact;
    private javax.swing.JLabel etiquetancontact1;
    private com.github.lgooddatepicker.components.DatePicker f_nac_cambio;
    private com.github.lgooddatepicker.components.DatePicker fecha_nac;
    private javax.swing.JPanel infoPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField num_contact;
    private javax.swing.JTextField num_contact1;
    private javax.swing.JComboBox<String> opcionDeporte;
    private javax.swing.JComboBox<String> opcionDeporte2;
    private javax.swing.JComboBox<String> opcionDeporte3;
    private javax.swing.JTabbedPane opciones;
    private javax.swing.JLabel recordatorio;
    // End of variables declaration//GEN-END:variables

    private void cargarLista() {
        DAOPersona cargar_info = new DAOPersona();
        personas = cargar_info.verInformacion();

    }

    public void rellenarDeporte() {
        
        DAODeporte cargar_Deportes = new DAODeporte();
        listaDeportes = cargar_Deportes.verDeportes();
        //System.out.println("listaDeportes: " + listaDeportes);
        for(Deporte d: listaDeportes){
            opcionD.addElement(d.getNombre());
            opcionD2.addElement(d.getNombre());
            opcionD3.addElement(d.getNombre());
        
        }
    }
}
