/*
 * 
 */
package grafica;

import DAO.DAODeporte;
import DAO.DAOPersona;
import com.mycompany.polideportivo_alejandro.Persona;
import com.mycompany.polideportivo_alejandro.Usuario;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author usuarioDAW
 */
public class ventUsuario extends javax.swing.JFrame {
     private Usuario usuario;
     List<String> deportes= new ArrayList();
     Persona p = null;
    /**
     * Creates new form ventUsuario
     */
    public ventUsuario(Usuario u1) {
        initComponents();
        String dp = "";
        Boolean esPrimero=true;
        this.usuario= usuario;
       
        DAODeporte dao = new DAODeporte();
        deportes= dao.mostrarDeporteaPesona(u1.getUsername());
        dp ="No hay deportes para este usuario";
        for(String d: deportes){
            if (esPrimero) {
                dp = "";
                esPrimero = false;
            } 
            
            dp= dp + d + "\n";
        }
        DAOPersona dao2= new DAOPersona();
        p = dao2.verInformacionPersona(u1.getUsername());
        categ.setText(p.getCategoria().toString());
        Nombre.setText(u1.getUsername());
        deport.setText(dp);
        deport.setEnabled(false);
        categ.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        NCategoría = new javax.swing.JLabel();
        categ = new javax.swing.JTextField();
        NDeporte = new javax.swing.JLabel();
        Visualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        deport = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NCategoría.setText("Categoría");
        jLayeredPane1.add(NCategoría);
        NCategoría.setBounds(10, 200, 80, 30);

        categ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categActionPerformed(evt);
            }
        });
        jLayeredPane1.add(categ);
        categ.setBounds(150, 200, 230, 40);

        NDeporte.setText("Deporte");
        jLayeredPane1.add(NDeporte);
        NDeporte.setBounds(10, 50, 90, 30);

        Visualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Visualizar.setText("Visualizar");
        Visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Visualizar);
        Visualizar.setBounds(220, 370, 110, 50);

        deport.setColumns(20);
        deport.setRows(5);
        jScrollPane1.setViewportView(deport);

        jLayeredPane1.add(jScrollPane1);
        jScrollPane1.setBounds(110, 20, 380, 110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categActionPerformed
        
    }//GEN-LAST:event_categActionPerformed

    private void VisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarActionPerformed
       String categoria= categ.getText();
        AuxiliarUsuario u2 = new AuxiliarUsuario(categoria);
        u2.setVisible(true);
    }//GEN-LAST:event_VisualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NCategoría;
    private javax.swing.JLabel NDeporte;
    private javax.swing.JLabel Nombre;
    private javax.swing.JButton Visualizar;
    private javax.swing.JTextField categ;
    private javax.swing.JTextArea deport;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
